name: Automation Pipeline

on:
  repository_dispatch:
    types: [run-automation]

jobs:

  selenium-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Automation Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Clone Application Repository
        run: |
          git clone https://github.com/ALamin068/inventoryapp.git

      - name: Start Spring Boot Application
        run: |
          cd inventoryapp

          chmod +x mvnw

          echo "Starting Spring Boot application..."

          ./mvnw spring-boot:run > app.log 2>&1 &

          APP_PID=$!

          echo "Spring Boot PID: $APP_PID"

          sleep 60

          echo "Checking if application is reachable..."

          curl http://localhost:8080 || true

          echo "===== APPLICATION LOGS ====="

          cat app.log

      - name: Run Selenium Tests
        run: mvn test
