name: Automation Pipeline

on:
  push:
    branches:
      - main

jobs:

  selenium-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Automation Repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Clone Application Repository
        run: |
          git clone https://github.com/ALamin068/inventoryapp.git

      - name: Start Spring Boot Application
        run: |
          cd inventoryapp
          chmod +x mvnw
          nohup ./mvnw spring-boot:run > app.log 2>&1 &

          echo "Waiting for application to start..."

          for i in {1..30}; do
            if curl -s http://localhost:8080 > /dev/null; then
              echo "Application started successfully!"
              break
            fi

            echo "Still waiting..."
            sleep 5
          done

          cat app.log

      - name: Run Selenium Tests
        run: mvn test
