name: Automation Pipeline

on:
  push:
    branches:
      - main

jobs:

  selenium-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Automation Repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Clone Application Repository
        run: |
          git clone https://github.com/ALamin068/inventoryapp.git

      - name: Start Spring Boot Application
        run: |
          cd inventoryapp
          chmod +x mvnw
          ./mvnw spring-boot:run &
          sleep 40

      - name: Run Selenium Tests
        run: mvn test
